name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    types: [ opened, edited, synchronize, reopened ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup JVM and SBT
        uses: coursier/setup-action@v1.3.5
        with:
          jvm: corretto:21.0.3.9.1
          apps: sbt

      - name: Clean Build Test
        run: sbt +clean +test
