name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
    types: [ opened, edited, synchronize, reopened ]

jobs:
  placeholder:
    name: Placeholder job
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Runner ${{ runner.environment }}"
        shell: bash